apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfuture
  labels:
    app: mfuture
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mfuture
  template:
    metadata:
      labels:
        app: mfuture
        tier: mfuture
    spec:
     containers:
      - name: mfuture
        image: eunjinchoi11/mfuture:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: mfuture
---
apiVersion: v1
kind: Service
metadata:
  name: mfuture
  labels:
    app: mfuture
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: mfuture
    tier: mfuture
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvol-1
  # storageClassName: gluster-heketi
  labels:
    app: mysql
    tier: database
spec:    
  accessModes:
   - ReadWriteOnce
  resources:
     requests:
       storage: "12Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
   app: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
   matchLabels:
     app: mysql
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mfuture!
        - name: MYSQL_DATABASE
          value: mfuture
        - name: MYSQL_USER
          value: eunjin
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data-vol
          subPath: mysql-data
        livenessProbe:
          exec:
           command: ["mysqladmin","ping"]
          initialDelaySeconds: 120
          timeoutSeconds: 10
      volumes:
      - name: mysql-data-vol
        persistentVolumeClaim:
          claimName: gvol-1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  labels: 
   app: mysql
   tier: database
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 30306
  selector:
    app: mysql
